### ISSUE TITLE
Add other domains owned by admiral?

### ISSUE THREAD

**Issue by KeenRivals** [paulgb/BarbBlock#4]
Many other domains were found that are owned by Admiral and point to the same IP as #1. There's a list at https://pgl.yoyo.org/adservers/admiral-domains.txt

**Comment by paulgb** [comment]
Thanks for this! I'll have a look when I'm at a computer

**Comment by tofof** [comment]
That list is woefully incomplete. See [my comment here](https://github.com/reek/anti-adblock-killer/pull/2502#issuecomment-277863986) for some analysis. Click the reverse-domain links I provide (e.g. [ipv4info for functionalclam.com](http://ipv4info.com/ip-address/sc98ee1/104.155.48.223.html/functionalclam.com/#_)) and you can see how deep this rabbit hole goes, and that's just for a single ip.

Sample admiral domains not in that list:
[btez8.xyz](http://btez8.xyz/)
[innocentwax.com](http://innocentwax.com)
[completecabbage.com](http://completecabbage.com)
[4jnzhl0d0.com](http://4jnzhl0d0.com/)
[h78xb.pw](http://h78xb.pw/)

**Comment by mvasilkov** [comment]
Let's kill the whole Admiral thing with fire!

**Comment by paulgb** [comment]
I've merged #8 which adds more Admiral domains, if there are still some missing I'm happy to add them as they are discovered

**Comment by mirague** [comment]
I support adding all domains pointing to the same content - it's likely all these domains would eventually have found their way into EasyList in the first place. Might be less likely now.

**Comment by JamyDev** [comment]
Maybe block that IP too in anticipation of more domains being added?

**Comment by tofof** [comment]
#8 is still not even close.

It has...
---
* Some but not all - e.g. breezybath.com - of the domains currently on [104.155.48.223](http://ipv4info.com/ip-address/sc98ee1/104.155.48.223.html) (the same ip that unknowntray.com is served from)
* Some but not all - e.g. axiomaticalley.com - of the domains currently at [146.148.6.205](http://ipv4info.com/ip-address/s1aa405/146.148.6.205.html)
* Some but not all - e.g. btez8.xyz - of domains currently at [35.186.249.84](http://ipv4info.com/ip-address/s43b0ac/35.186.249.84.html)

It's missing...
---
* owlsr.us and 65+ other domains that [have been](https://www.threatcrowd.org/ip.php?ip=104.196.29.119) or are currently on [104.196.29.119](http://ipv4info.com/ip-address/se262d3/104.196.29.119.html/owlsr.us/#_)
* roastedvoice.com and 64 friends from [146.148.79.27](https://www.threatcrowd.org/ip.php?ip=146.148.79.27)
* 17ars.xyz and past domains hosted by [52.39.21.213](https://www.threatcrowd.org/ip.php?ip=52.39.21.213) but not photos.hollywood.com that's [there now](http://ipv4info.com/ip-address/s9ba8c9/52.39.21.213.html)
* lewdwind.com and 20+ domains formerly at [104.155.177.112](https://www.threatcrowd.org/ip.php?ip=104.155.177.112)
* spottysense.com and many formerly at [54.187.68.112](https://www.threatcrowd.org/ip.php?ip=54.187.68.112)
* and [more](https://www.threatcrowd.org/ip.php?ip=52.43.106.30) 
* and [more](https://www.threatcrowd.org/ip.php?ip=52.43.161.34) 
* and [30 more](https://www.threatcrowd.org/ip.php?ip=104.198.13.121) 
* and [commoncannon.com and a dozen more](https://www.threatcrowd.org/ip.php?ip=104.198.107.72)
* and [more](https://www.threatcrowd.org/ip.php?ip=104.154.148.163) 
* and [chickenstation.com and 100 others](https://www.threatcrowd.org/ip.php?ip=146.148.6.205)
* and [these](https://www.threatcrowd.org/ip.php?ip=52.88.227.7) 
* and [those](https://www.threatcrowd.org/ip.php?ip=52.25.239.10) 
* and [frailoffer.com and friends](https://www.threatcrowd.org/ip.php?ip=54.200.18.113) 
* and [granodiorite.com and others](https://www.threatcrowd.org/ip.php?ip=146.148.79.27) 
* and [43 more except there's an innocent one too](https://www.threatcrowd.org/ip.php?ip=104.196.220.175)

...  I think that demonstrates my point.  Someone else want to take a turn?

You just have to walk the related domains on a tool (like threatcrowd) that lets you do so easily. 

It's trivial to verify these even when you're learning the naming patterns, since they all serve up [the](http://wirecomic.com/1d6331ea1c38725b2c5365d8052ef38fd02448941a9ebc9c992810e68fe3094dadd4b950a8fd3b4b2f7d080c) [same](http://btez8.xyz/0018aa644424254f733b14cc2d656b361bfbdb7085745ae38df94c2545f529626c1deeb3fd996f10b84c80c7) [image](http://truthfulturn.com/6f73318887c8e95c7bbf92d29ea78c6ac9a1a92c5dc624190db1fc79d1800b97bacf012b0d36781db9bb054a)

Some starting points that I haven't already exhausted above include...
tzwaw.pw
0D7DK.XYZ
pz37t.xyz
3jsbf5.xyz - beware, there's at least one domain ([apstylebook.com](https://www.threatcrowd.org/ip.php?ip=52.42.177.85)) that'd be a false positive.

The biggest problem is that they use google/amazon hosting and so you can't trivially blacklist everything that resolves into their IP space.

**Comment by lol768** [comment]
@tofof Given the ones that I have seen seem to use valid SSL certs from Let's Encrypt, do you think crawling the CT logs is a viable way of checking for these?

**Comment by anon182739** [comment]
What about doing it the other way around? As you said, it's trivial to verify a domain. What about checking all suspicious domains? If one is found, it's sent to some central server to be added to the list. Another way would be to just blacklist the IPs. This would have some false positives, but if it becomes a default filter for ublock/adblock it would have the effect of forcing them to clean up their IP ranges. But really, how often do you have a legitimate reason for loading random .js from a .xyz domain?

@lol768 
They issue hundreds of thousands of certificates each day, but if you manage to get the first filtering down it's feasible, then you can use DNS to filter out more.

@mvasilkov 
I don't think that's feasible. Maybe by sending abuse notices to the registrars, since they care more about quantity than quality.

**Comment by anon182739** [comment]
Also, playing cat-and-mouse with domains is not really a problem. It costs at least $1 to register one, and much less to find and block it.

**Comment by zymase** [comment]
Reading @tofof I realize that indeed the BarbBlock, if it has the merit to exist, does not include and may never include should it be but a far more exhaustive list, for the sole reason that such a list seems to be a challenge.

Computing-fiction: what would be fantastic would be to have the ability to define a checksum of the famous landing-picture and block connections on that criteria (provided the image doesn't change a pixel here and there). Otherwise, how on earth can a list be conceived otherwise than with try-and-succeed/try-and-fail policy? It's just impossible. We are facing networks as dirty as bots.

**Comment by paulgb** [comment]
Actually, @lol786's suggestion sounds like a great idea for keeping track of new registrations from this company. It could be automated as a nightly script.

**Comment by zymase** [comment]
> Given the ones that I have seen seem to use valid SSL certs from Let's Encrypt

"_Seem_" ... if the result is equivalent to cutting a hand because of a whitlow, I'd be more than cautius with that very way of proceeding.

**Comment by paulgb** [comment]
That's just a way of narrowing down the search space; we'd still verify that the domain behaved like the others.

I'd like to keep this to a pure domain blacklist, as opposed to running code on the client, for a few reasons: 1. it's more portable to existing blocking extensions, 2. it's more performant, and 3. I'm more comfortable with the legal defensibility (I am confident that a passive blacklist can never be illegal; I don't want to speculate about the legality of a more active client-side approach)

**Comment by zymase** [comment]
Well, @paulgb you have the merit of having built and a centralized list (even if improvable), a place to discuss it and moreover an open-mind to carry on and develop the list. I do congratulate you for this initiative and for your work. I stay tuned of course and at this time and in order to avoid a chaotic result I stick on your list updated with all others included in my uBlock Origin settings, once a day.

let's keep on doing it!

**Comment by anon182739** [comment]
@zymase
You can just check the image dimensions, or the length of the body. This works for me:
`def isAdmiralDomain(domain):
    try:
        response = requests.get('https://' + domain)
    except:
        return False
    if len(response.text) == 179:
        return True
    else:
	return False`
>Otherwise, how on earth can a list be conceived otherwise than with try-and-succeed/try-and-fail policy? It's just impossible. We are facing networks as dirty as bots.

Start of with the LE cert list. Filter away anything that doesn't end with .com, .xyz, or .pw. Issue DNS queries for everything. If the whois isn't protected, remove it. If they're not using whatever registrars they're using, remove it. Then use tor/proxies (it's kind of counter productive for them to block IPs) for the final verification. 

Why not literally treat them as bots? I don't have any, but SMTP accounts are allegedly quite cheap. What if you'd just send bulk abuse notices to the registrars and accuse them of being C2 servers for some botnet? They generally don't care if the notices are valid, they only care about the quantity of notices they're getting.

@paulgb 
>That's just a way of narrowing down the search space; we'd still verify that the domain behaved like the others.
And this job can be automated easily, as long as the domain can be identified once you can put it in the list forever.

**Comment by anon182739** [comment]
GitHub stripped away the formatting, so you need to add some newlines and indentation.
The images are identical right now.
CRC32: 8db019c1
MD5: 681e062bb33b9ba28f3427e7283c81a8
SHA1: 3fcf7e14e92043a00926d340d45778b618bc87a9
SHA2: 32afacb9285649aa4af43ea03e7cd9a522aa3e6d0554a2dabe308fac4531be5f

**Comment by zymase** [comment]
@anon182739 your first steps may be valuable for coders of which I am not unfortunately. I try to embrace the problematic conceptually but I'd be unable to translate an idea, a solution into code. At my little level a target is defined with a domain name and/or an IP but here we have hundreds, maybe thousands of domains all calling a same goddam static picture with a dynamic name. This is one scenario where I'd really love to be smarter and able to code.  Maybe are you on the right path, I don't know.

**Comment by anon182739** [comment]
Another identifying mark is the robots.txt, which is unlikely to change:
`User-agent: *
Disallow: /`

The 404 page seems nonstandard:
`404 page not found`
(it's not HTML)
`Content-Type:"text/plain; charset=utf-8"`

The registrar is enom for the .com domains and namecheap for the .xyz and .pw domains. 

They all use the same 4 nameservers. You should be able to enumerate from that, it's an uncommon combination. 
NS-1212.AWSDNS-23.ORG
205.251.196.188
NS-1627.AWSDNS-11.CO.UK
205.251.198.91
NS-305.AWSDNS-38.COM
205.251.193.49
NS-697.AWSDNS-23.NET
205.251.194.185

**Comment by anon182739** [comment]
@zymase
You want to block the domain names. You can get a new IP for almost nothing, getting a new domain name costs some money. The picture's name changes, but the site's structure is the same.

**Comment by anon182739** [comment]
Also worth noting is that you can query however many admiral domains you want with Tor. If they start blocking IPs, then their ads won't work anymore.

**Comment by zymase** [comment]
@anon182739 ,

> You want to block the domain names. You can get a new IP for almost nothing, getting a new domain name costs some money. The picture's name changes, but the site's structure is the same.

That's not what I meant. Point is as everyone I can block domains, IPs, IP ranges but I don't understand -- coder or not -- what reference to consider in this scenario. It's not because I cannot understand that it means its not understandable of course. There's nothing but a picture, we all know it and I've repeated it at least a dozen times, and besides your picture size checking and the nameserver approach, where, what to "hold", see what I mean? But I'll stop laying the obvious, doesn't help. 

The point is and remains that an unknown number of domains, when called, resolve to one picture, as if a sonar detected hundreds of echoes all pointing to a wreck 30,000 feet below sea level. Above my understanding.

**Comment by anon182739** [comment]
@zymase 
I don't understand what you're trying to say. You can look at a domain and see if it has that picture. If it does, it also has the script we want to block.

The domains don't resolve to the picture. The domains resolve to Google IPs, which then serve that picture. The domains all point to different IPs.

The purpose is to block the script they use, the easiest way to do this is to block the Admiral domains so they can't serve the script.

**Comment by tofof** [comment]
anon182739 wrote:
> Filter away anything that doesn't end with .com, .xyz, or .pw.

I wouldn't use such a filter. First of all, Admiral has at least one .us domain that I've already prominently mentioned in this thread; it's literally the first domain I name as 'missing'. Second, there's no reason to think they won't expand to other TLDs. Nine months ago, noone had spotted any .xyz Admiral domains - I doubt they were using them yet.

**Comment by zymase** [comment]
@anon182739 the problem is not to know if a domain links to the picture, the problem is to now on what criteria build a list. we're not going yo analyze the whole web domain after domain to see the ones which point to that picture, right? So on what basis will the list be built other than adding the finds of participants : we're not in a hunt or a tombola, right? So on what criteria will this list be built? It's not like phoning "Hey, I found another one" ... there must be a common point to all domains pointing to that picture, or is there?

**Comment by tofof** [comment]
@zymase 
You've stated that you don't understand and are not a coder. It's acceptable to be interested, to use the emoji-response features, etc, but please don't clutter a single-issue thread with philosophical meanderings, well-wishings, tortuous analogies, and otherwise "laying the obvious," whatever that means.

To address your final point:
No, there is no reason to think that there must be a common resource, accessible to the public, that would identify all such domains. 
If instead you mean that there must be a reason for these domains? Yes, the reason is that Admiral owns them and happens, for now, to serve the same content from all of them. They could just as easily serve nothing but a 403 or 204 error code, or just blackhole connections. 

The list's criteria are already stated: it is a list of domains who have misused DMCA takedowns to attempt removal from other lists. This issue is suggesting that affiliated domains that are owned by the same company and used for the same purpose be included alongside the singular example named on a DMCA takedown thus far. The criteria for inclusion that's being proposed, then, is similarly obvious: Admiral-owned domains that appear to serve the same (lack of) content and presumably host the scripts used in serving advertising at affiliated websites.

Quite contrary to your assertion, such a list, if built, will be built exactly the same way all other advertising-blocking lists are built: on the finds of participants reporting "I found another one".  The starting points are found when an Admiral-protected website (e.g. thewindowsclub.com) uses scripts hosted on an Admiral server to display its contents.

I have already outlined the best possible way to find more Admiral domains given a starting domain: by using tools meant for that, i.e. tools that identify spatially- and temporally-related domains.

**Comment by paulgb** [comment]
@tofof Thanks for the analysis you've been doing, I have only been skimming this conversation while working on providing all the blacklist formats people want but now that that's done I want to take a real stab at automating some of this.

**Comment by anon182739** [comment]
@zymase
>We're not going to quest the whole web, domain after domain to see the ones which point to that picture, right?
You can narrow it down enough so you don't need to check the entire web.
@tofof
What's wrong with scraping DNS/cert lists? They can easily make sure that 1 domain = 1 ip and avoid tainting each other, it's non-trivial to make it harder to verify the domains.
@paulgb 
I'm already working on it, I've managed to hack together a python script that does the job. Should I post it here, or is 'security by obscurity' better?

**Comment by anon182739** [comment]
@zymase
>We're not going to quest the whole web, domain after domain to see the ones which point to that picture, right?

You can narrow it down enough so you don't need to check the entire web.
@tofof
What's wrong with scraping DNS/cert lists? They can easily make sure that 1 domain = 1 ip and avoid tainting each other, it's non-trivial to make it harder to verify the domains.
@paulgb
I'm already working on it, I've managed to hack together a python script that does the job. Should I post it here, or is 'security by obscurity' better?

It turns out they only have 159 domains apparently, all the "different starting points" were somehow interlinked.

https://pastebin.com/6mPnXBiR

**Comment by paulgb** [comment]
Great stuff, is this from the CT log or just from grabbing the IPs already found?

Let's keep the script apart from this, but if you're not a paying GitHub user I can create a private repo and add you to it so we can collaborate.

**Comment by anon182739** [comment]
This naming scheme is interesting.
If you visit any admiral domain (example: http://abandonedclover.com http://abruptroad.com) you get that image:
http://abandonedclover.com/6f044848f5e9030b6fd409a7e153defd6d8c4e58fb082a44da549ed3e421f9755aedb08132895be1e0d578e7
But each time you refresh the page, you get a new URL:
http://abandonedclover.com/f1e5b5d86bcceb851312e5cc5f7bce26bb10ab951c152cb63a5068954caaa20d196ab3a042d306f561b71c22
You can use it multiple times, and across different domains. I really wonder how this works? Is it a signature of some sort? 
@paulgb
This is from scraping one domain (hfc195b.com) and recursively querying the results from threatcrowd. It seems to cover all of the "starting points" listed though, except for 0d7dk.xyz pz37t.xyz 3jsbf5.xyz that weren't reachable. So this _should_ be all of their domains.
Sure, or I can send it in a PM if you want. It's not of much use now though.

**Comment by paulgb** [comment]
Sure, a PM works for me. My email is paulgb@gmail.com

Cheers.

**Comment by anon182739** [comment]
Oh, you can't send GitHub PMs anymore apparently.
Gmail filters any anonymous e-mail addresses since they're used for spam. If you already have github premium, it's probably easier to do it that way.

**Comment by paulgb** [comment]
Ok, I created a repo.

**Comment by anon182739** [comment]
I can't see anything. Where do I get the notice?

**Comment by paulgb** [comment]
Try this link: https://github.com/paulgb/iptool/invitations

**Comment by anon182739** [comment]
Thanks, it works now.

**Comment by anon182739** [comment]
There might be a point to running it without Tor, it's a bit finicky and seems to give some false negatives. This could be intentional, but I don't think so since I could get them with Tor on a second try. Some IPs gave really many domains, one or two were probably responsible for 70% of the domains.

**Comment by anon182739** [comment]
Interesting, shodan gives me IPs that don't have any domain names registered according to threatcrowd
https://pastebin.com/w3HZ4Ker
query: "X-Datacenter: Content-Length: 179 Date: Mon 2017"
Replace Mon by any other week day, it's just to split it up so it doesn't get past 2 pages which is the free account limit, you can also add month if you don't want to create account

**Comment by tofof** [comment]
> It turns out they only have 159 domains apparently, all the "different starting points" were somehow interlinked.
> https://pastebin.com/6mPnXBiR

FFS. 
No, that list is incomplete.
=================
It doesn't "turn-out" that it's done already. It turns out that people are willing to pass off trivially incomplete lists with claims of completeness that will be vacuously repeated to the detriment of any effort to build such a list.

It's missing tons of the ones I already pointed out.  It includes false positives, too, like its literal first lines, which are google and not Admiral domains. And it has double entries.

It is barely any different than the list already attached to this repository.

It's missing, at minimum:
================
* owlsr.us, al102.xyz, 3jsbf5.xyz, and [all the others](https://www.threatcrowd.org/ip.php?ip=104.196.29.119) that [I already pointed out](http://ipv4info.com/ip-address/se262d3/104.196.29.119.html/owlsr.us/#_) from the very first line of my earlier missing list.

* It's missing roastedvoice.com, and presumably the others I already pointed out from the SECOND line of my missing list.

* It's missing 17ars.xyz, and presumably the others I pointed out on the THIRD line of my earlier list.

* lewdwind.com and presumably the others I pointed out on the FOURTH line of my earlier list.

* b6227.xyz and presumably many others from the SIXTH line of my earlier list.

* granodiorite.com and presumably many others from that line. 

* 0D7DK.XYZ and others from that starting point.
* pz37t.xyz and others from that starting point.
* 3jsbf5.xyz and others from that starting point.

And that's just the ones I **explicitly named as examples already** of what was missing before.

I am very tired of people posting short lists and saying "work's done, this is all of them!" I especially can't wait until these singular examples get added without adding any of the others from all the links I already provided, much less any from anyone else making even the slightest attempt.

**Comment by tofof** [comment]
@anon182739 
> What's wrong with scraping DNS/cert lists? They can easily make sure that 1 domain = 1 ip and avoid tainting each other, it's non-trivial to make it harder to verify the domains.

1) I never said a single thing against scraping cert lists, please take your fallacious statements elsewhere.
2) It is in fact trivial to make it harder to verify these domains, and I have already provided an example of two ways they could to do it **in this very thread**. Again, please peddle falsehoods elsewhere.

**Comment by anon182739** [comment]
@tofof 
Rude.  
owlsr.us  
Honest mistake, it probably timed out because it **IS** in there, it was just marked as "not admiral" because the request timed out or something similar. Tor is somewhat finicky, but if you have a cleaner IP you can re-run the script (ask @paulgb to add you)  

>al102.xyz, 3jsbf5.xyz  
dead  

roastedvoice.com  
>This Domain Name Has Expired - Renewal Instructions.  

17ars.xyz  
dead  

lewdwind.com  
>This Domain Name Has Expired - Renewal Instructions.  

b6227.xyz  
dead  

granodiorite.com  
>This Domain Name Has Expired - Renewal Instructions.  

0d7dk.xyz  
dead  

pz37t.xyz  
dead  

3jsbf5.xyz  
dead

Worth noting is that a fair amount of the ones marked as dead were checked, but marked as not-admiral because they were, well, dead. 

>It includes false positives, too, like its literal first lines, which are google and not Admiral domains.

They are admiral domains. They serve the Admiral malware and act as C2 server for the botnet. How are they not admiral domains?

>And it has double entries.

Caused by differences in case, it can be resolved by adding a line in the script.

**Comment by anon182739** [comment]
Checking who.is history (make sure to disable JS otherwise it fetches it again), you can see that the dead domains have expired. Except 17ars.xyz apparently, unless someone else registered it.

Isn't it a security risk to be loading random JS from domains that they're not taking very good care of? They're not attaching a hash from what I can see.

**Comment by anon182739** [comment]
>Except 17ars.xyz apparently

Name  
REACTIVATION PERIOD  
Organization  
NAMECHEAP  
Address  
11400 W. OLYMPIC BLVD, SUITE 200  

Well, that explains that.

**Comment by tofof** [comment]
@anon182739 
My apologies. First, thank you for your work. Please forgive my outburst; literally the very first example I provided (one I know *is* live and *is* Admiral) was omitted. That, with the immediate appearance of so many more omissions, caused me to overstate things.

Given that you've verified that your tool has timed out on at least one positively-Admiral domain, can I ask what assurance you have that others that I haven't manually called out didn't get similarly classified?

**Comment by anon182739** [comment]
>I never said a single thing against scraping cert lists, please take your fallacious statements elsewhere.

I'm sorry, I missed your reply on it. But what are your thoughts on it? You could dynamically add domains to the filter, so whenever a .us domain is spotted you add it to the filter. It would still be useful to narrow things down.

>It is in fact trivial to make it harder to verify these domains,

Harder? Yes. Hard? No. I used the wrong word there.
>and I have already provided an example of two ways they could to do it in this very thread.

I missed them. But it's hard to obfuscate it indeterministically, they will still have some kind of recognizable pattern. It's enough to find the pattern once, then that domain's useless forever and you've costed them $1.

**Comment by tofof** [comment]
@anon182739 
I think that the idea of scraping cert lists is potentially clever. I see a few potential hurdles, however.
* Sheer volume of certs per day is large. Filters might help, but I think they're more likely to be more trouble than they're worth - if you fail to include e.g. .us and then at some future point find Admiral domains with that TLD, now you have to .. what, go back through the cert logs to some starting point and rescrape a whole set of domains you'd filtered before? Doesn't seem like filtering is a meaningful reduction in workload at that point.
* If the domain purchase and the cert application happen concurrently, before DNS has populated, does a verification script risk hitting the domain before it's "live" and miscategorizing it as non-Admiral?

The ways to make things harder I'm referring to: at any point, Admiral can just blackhole incoming traffic* or serve up http status codes instead of the helpful image saying "Hi I'm Admiral". Particularly when they can put their scripts behind completely random filenames.

*incoming traffic other than to their randomly-named-at-creation script, of course

At some point they have to actually use their servers, and we can see references to the scripts "in the wild" on other pages, and catch them that way. But that's the super-slow super-manual way of doing it.

Fundamentally I don't think I agree with your assertion that there has to be a pattern that's externally recognizable. It's very beneficial to us right now that there is, but I don't think that has to be the case at all. 

I do, however, wholeheartedly agree that going after domains is worthwhile. It definitely costs less for us to hunt them than it does for them to buy them, at least in the current balance.

**Comment by anon182739** [comment]
@tofof
None, except that Tor isn't that finicky. If you have a more reliable internet connection you can run the script. Security through obscurity is probably useless, it was just an instinctive reaction, https://pastebin.com/tsBH5s7A
> For the unaware: Admiral tracks hits to their domains and blocks you if you have too many in too short a period, presumably to defeat exactly this sort of listbuilding.

Are you sure? I don't think that happened, but it's possible the API timeout saved me from it. In any case, you can use Tor stream isolation for each requests. If they block Tor, that's just a net win since it means some people get "free" adblocking and proxies are plentiful anyway.

Do you have any other information/documentation like this about admiral?

**Comment by tofof** [comment]
Regarding those googleusercontent.com lines - Yes, they serve up Admiral content right now, but that's just because Admiral is hosting on Google Cloud platforms. I maintain that they're false positives, at least until their use in the wild can be verified.

[Google+, AdWords, Google Fonts](https://en.wiki-domains.net/wiki/googleusercontent.com), and some [Google Translate content](https://news.ycombinator.com/item?id=6112831) all gets served up from googleusercontent.com servers.

**Comment by tofof** [comment]
@anon182739 
> Are you sure? [that Admiral blocks you if you hit them too often]
I'm not 100%, in that I haven't verified that behavior this week. I make that claim from my experiences trying to pin down their bootstrapper 6 months ago, when that definitely was the case, and I was getting served explicit error messages stating that I was being deliberately blocked. It's possible that you have to be hitting the script file or something other than the landing image to trigger that, though.

**Comment by anon182739** [comment]
>Sheer volume of certs per day is large.
I checked. It was large, but not very large. 100k-200k a day, this is about 2 per second. Certainly manageable.
>Filters might help, but I think they're more likely to be more trouble than they're worth - if you fail to include e.g. .us and then at some future point find Admiral domains with that TLD, now you have to .. what, go back through the cert logs to some starting point and rescrape a whole set of domains you'd filtered before? Doesn't seem like filtering is a meaningful reduction in workload at that point.

You only have to go back and re-check the ones with .us domains. You can check the registration date of the first ones spotted in the wild and go back from there.

>If the domain purchase and the cert application happen concurrently, before DNS has populated, does a verification script risk hitting the domain before it's "live" and miscategorizing it as non-Admiral?

You need to have a valid DNS entry for Let's Encrypt, it's all automated.

>The ways to make things harder I'm referring to: at any point, Admiral can just blackhole incoming traffic*

They still have to receive the HTTP request, so they can't blackhole it entirely - they still need to send some TCP packets to be able to listen.

>or serve up http status codes

And then those will be identifiable, like they are now. Or they'll all be random which will also look strange - why would an nginx server send an apache 404?

>Particularly when they can put their scripts behind completely random filenames.

The filenames are valid for all domains right now.  
As said before, they only need to have a detectable signature once to be blocked.  

> we can see references to the scripts "in the wild" on other pages, and catch them that way. But that's the super-slow super-manual way of doing it

That can be automated too. Compile a list of sites that use admiral, see what domains they link to. Admiral is free of charge to use, and you can use e.g. shodan if you ever find a pattern for the bootstrapper to find domains using it.

>Admiral can just blackhole incoming traffic* or serve up http status codes instead of the helpful image saying "Hi I'm Admiral".

I'm not so sure about this. When a domain registrar receives an abuse notice for a randomly generated .xyz domain registered with whoisguard that only serves randomly named obfuscated JS files, what will they think?

>I maintain that they're false positives, at least until their use in the wild can be verified.

They're only serving admiral content though. I maintain that they're valid admiral domains, since they're functioning exactly like admiral domains besides for being unused.

>I was getting served explicit error messages stating that I was being deliberately blocked

Did this block you from getting the actual scripts too? How long did it last for? Would it be possible to block all tor exit nodes/similar?

**Comment by anon182739** [comment]
Also, the robots.txt will still be identifiable unless they want to get revealed by internet archive.

**Comment by tofof** [comment]
>The filenames are valid for all domains right now.
That's interesting, I missed that earlier. 

>Did this block you from getting the actual scripts too? How long did it last for? Would it be possible to block all tor exit nodes/similar?
Yes, I distinctly remember that it blocked me from getting the scripts. I also remember it unsurprisingly caused some sort of failure to be able to load Admiral-protected content on affiliated sites. The first one lasted fewer than 10 minutes, another lasted at least 2 hours. No, I doubt it would have had any effect against traffic routed through (different) Tor exit nodes - my recollection is that it was a simple "we've timed you out" sort of error page and didn't seem very sophisticated.

**Comment by tofof** [comment]
@anon182739 

> Also, the robots.txt will still be identifiable unless they want to get revealed by internet archive.

How so? A simple block-everything robots.txt is hardly unique to Admiral.

**Comment by anon182739** [comment]
>The first one lasted fewer than 10 minutes, another lasted at least 2 hours.

So in other words, it increases on subsequent violations.
>I also remember it unsurprisingly caused some sort of failure to be able to load Admiral-protected content on affiliated sites.

How does that work? If you block the servers, won't that have the same effect?
>No, I doubt it would have had any effect against traffic routed through (different) Tor exit nodes

You're misunderstanding me. What if you run a script to make sure all Tor exit nodes and open proxies get blacklisted on purpose? It will decrease the appeal of Admiral if webmasters know that anyone using  a proxy/VPN can't read their site.

I tried to get banned by force refreshing the page some hundred of times, how many requests did you do?

>How so? A simple block-everything robots.txt is hardly unique to Admiral.

It's uncommon, so it helps filtering. How common is blackhole+namecheap+whoisguard+robots+lets encrypt?

**Comment by anon182739** [comment]
`                                 Dload  Upload   Total   Spent    Left  Speed`  
`  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0curl: (52) Empty reply from server`  
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`  

Are they already blacklisting, or is it just Tor?

**Comment by tofof** [comment]
> It's uncommon, so it helps filtering. How common is blackhole+namecheap+whoisguard+robots+lets encrypt?
Ok, fair enough, as part of the rest of the pattern it's helpful.

> I tried to get banned by force refreshing the page some hundred of times, how many requests did you do?
I got it within a few dozen refreshes of the script at the time, probably within a 15-minute interval or so. Certainly nowhere near 100. 

> How does that work? If you block the servers, won't that have the same effect?
Yes, it does. If you outright blocked the Admiral servers, some Admiral-protected sites didn't serve any content; others still did. It depended on the bootstrapper that was used.

**Comment by anon182739** [comment]
>I got it within a few dozen refreshes of the script at the time, probably within a 15-minute interval or so. Certainly nowhere near 100.

Wild guess: they were banning VPN exit nodes left and right and decided to stop it  
>If you outright blocked the Admiral servers, some Admiral-protected sites didn't serve any content; others still did. It depended on the bootstrapper that was used. If you outright blocked the Admiral servers, some Admiral-protected sites didn't serve any content; others still did. It depended on the bootstrapper that was used.

How many different bootstrapper scripts are there? What did you find out about them? What's the point in blocking the servers if that just kills the site too?

**Comment by tofof** [comment]
> How many different bootstrapper scripts are there?

I have no idea. I know Admiral offers several different tiers/configurations of services, perhaps they're related to those, but that's just speculation.

> What did you find out about them?

Nothing helpful that I can recall; the few notes I took during the poking I was doing mostly have to do with killing the inline script after it was loaded, rather than the bootstraper.

> What's the point in blocking the servers if that just kills the site too?

That's what caused me to quit working on this at the time.

**Comment by anon182739** [comment]
How do they inject the ads again? Could you just block the re-injected images or similar?

**Comment by tofof** [comment]
I don't think Admiral directly injects ads except when it's configured to serve `less-intrusive' ones to replace the ads that it's protecting. All of my efforts were toward the script that takes over and blanks the page when it detects an adblocker. 

I'd like to show you an example, but right now I'm actually having trouble getting Admiral to function, i.e. to actually annoy me with a popup and blank the screen. I have a feeling there's a hack somewhere I'm forgetting to disable.

**Comment by anon182739** [comment]
The scripts have some kind of optimization layer, do you know what it is? Pagespeed supposedly only removes whitespace and the usual, but it's a pagespeed URL.
https://js.intercomcdn.com/frame.3db8f7f5.js
`!function(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={exports:{},id:r,loaded:!1};return e[r].call(o.exports,o,o.exports,t),o.loaded=!0,o.exports}var n={};return t.m=e,t.c=n,t.p="https://js.intercomcdn.com/",t(0)}(function(e){`
https://js.intercomcdn.com/shim.cada1405.js
`!function(n){function t(o){if(e[o])return e[o].exports;var r=e[o]={exports:{},id:o,loaded:!1};return n[o].call(r.exports,r,r.exports,t),r.loaded=!0,r.exports}var e={};return t.m=n,t.c=e,t.p="https://js.intercomcdn.com/",t(0)}({0:function(n,t,e){`
They begin in the same way.

**Comment by tofof** [comment]
No, I don't know what it is, but working on reversing minified code is honestly way out of my specialty.

**Comment by anon182739** [comment]
https://wordpress.org/plugins/admiral-adblock-suite/  
`public static function doesURIContainRandomFilename($uri, $seeds)`  
Does what it says on the tin if you're interested.

**Comment by anon182739** [comment]
It also has other interesting stuff, gives away some information about how it's structured internally. owlsr.us is used as gateway, it might have been specially registered for that purpose.
>Wordpress Plugin  
>Easy install. No JS code required. Proxy requests to minimize risk of adblocker intervention.

>Custom Integration  
>Proxy Requests through your own domain to minimize risk of adblocker intervention.

Also, there are lots of API endpoints we can use to identify domains.  
http://staging.owlsr.us/js?p=asd  
http://owlsr.us/record

**Comment by tofof** [comment]
@anon182739: thanks again for your script, it's very helpful. I've been playing with it for a bit now, and I notice a couple things.

Obvious statement: unfortunately, your script is limited by the threatcrowd data.
Less-obvious: there are domains that are Admiral that threatcrowd completely lacks.

For example:
https://otx.alienvault.com/indicator/hostname/2znp09oa.com shows profitrumor.com among the related domains, which is an Admiral domain. 

But unfortunately, threatcrowd's picture of that is a big zilch: 
[![profitrumor](https://user-images.githubusercontent.com/3980843/29301678-819884ea-8143-11e7-92c0-a87729e1ea94.png)](https://www.threatcrowd.org/domain.php?domain=profitrumor.com)

**Comment by anon182739** [comment]
Yes, it's a shame. What services are there to get all domains with a given nameserver? Because they all share the same 4 nameservers.

**Comment by anon182739** [comment]
https://otx.alienvault.com/otxapi/indicator/hostname/whois/2znp09oa.com Here, just parse this JSON and use as starting domains for the script, it doesn't matter that they're not in threatcrowd. (1 domain per line, no http before)

**Comment by tofof** [comment]
Yeah, just was looking at that myself, looks like it's possible to at least walk that api's space as well.

**Comment by anon182739** [comment]
@tofof No need for walking, since you can do queries on DNS name servers.
`grep -P '"domain": "[^"]+' --only-matching | cut -c 12-`

**Comment by anon182739** [comment]
https://pastebin.com/CYvL1GyJ
20 more

**Comment by anon182739** [comment]
I strongly believe these ones are the only ones that are active in the wild:
https://pastebin.com/Bu2gFH9J
I ran script that created 600 accounts and got the script URLs, these are the only ones in the list. The least common one (jadeitite.com) is present 8 times, the most common one (82o9v830.com) is present 20 times.

**Comment by paulgb** [comment]
On thing on the topic of unminifying code, etc.: In order for this project to be bulletproof should it end up in court, I can't include any links obtained that way. Since a judge is unlikely to be technically adept enough to understand nuance in this area, I'd rather keep a good distance from anything that could be made to sound like reverse engineering to someone non-technical.

The network-based approaches are defensible though, so as long as we stick to that route we'll be fine.

**Comment by anon182739** [comment]
Clean room reverse engineering is legal. So by analogy, you should be able to share domains you got from observing the script's behavior, but not by reverse engineering them.

If you're worried about the legal aspects, keep in mind that the CFAA is very broad. Bulk registering accounts could be illegal in theory, depending on the definition of "authorization".  
(a) Whoever—  
(2) intentionally accesses a computer without authorization or exceeds authorized access, and thereby obtains—  
(C) information from any protected computer;

**Comment by paulgb** [comment]
It's not just the CFAA that I want to steer clear from, it's also DMCA 1201 which was the basis of Admiral's takedown against EasyList.

In general I guess my stance is: given that there are many ways of obtaining the list, we should do it in the way that is least likely to be misunderstood by a judge.

**Comment by anon182739** [comment]
Are you worried about takedowns or legal responsibility?  
If the former, use a git provider based outside of the US (bitbucket is australian, launchpad is british, osdn is japanese, ow2 consortium is french, self-hosted gitlab onion is in the jurisdiction of anonymous proxy)
If the latter, use a throwaway account and Tor

**Comment by paulgb** [comment]
But that misses the goal of the project entirely! I'm not trying to evade any laws, quite the opposite. I'm trying to show that Admiral's interpretation of the law is incorrect, that it wouldn't hold up in court, and that they know that.

**Comment by anon182739** [comment]
If you're not violating any laws, avoiding takedowns is just a convenience thing. DMCA takedown notices are for copyright infringement, circumvention of technical protections as defined in 17 USC § 1201 isn't copyright infringement.

**Comment by tofof** [comment]
I agree with @paulgb that Admiral's interpretation of the DMCA - that an item in a list constitutes a 'copyright circumvention mechanism' - is incorrect, and should be challenged. I understood that to be the primary reason for the creation of this project: to invite, challenge, and disprove this legal theory.

Expanding the list to include related Admiral domains that appear to function identically to the DMCA-takedown'd one seems in line with that goal.  Particularly for a list created by crawling publically accessible networks and observing the content that Admiral willingly serves up (its landing page image).

**Comment by paulgb** [comment]
I agree with that interpretation @anon182739 but Admiral's stance is that it does and that's how we got here.

@tofof exactly

**Comment by tofof** [comment]
On the topic of reversing minified code - as far as I understand, none of that has been done in generating any of the list to this point. The list and addendum that @anon182739 has linked to is built from walking the recorded observations on threatcrowd - starting from a known Admiral domain, examining what IPs it was hosted on and what other domains were hosted on those IPs, and recursing, then examining for each domain its current public home page to see if it identifies itself as part of the Admiral protection scheme. 

Note that the content that Admiral domains serves explicitly covers such a use: "if you arrived here on accident and are not looking for information about this domain, feel free to hit back in your browser or close the tab." In other words, when we purposefully visit the domain and are exactly looking for information about it, that image is meant to be our answer. It spells out what type of content ("Javascript, HTML, CSS, video and images") is served and for what nominal purpose ("to control access to copyrighted content ... and understand how visitors are accessing their copyrighted content") it does so. Whether this is an honest summary of Admiral's use of these domains is another matter.

My mentions of reversing minified code were with respect to observing the behavior of the Admiral scripts themselves, and in historical context where I was examining those scripts in support of an entirely different project (Reek's Anti-Adblock). Also note that minification is not for the purposes of obscuring or defeating an observer; if it was, you wouldn't leave function names like "hasDisabledAdBlocker" intact. Minification is simply to reduce the size of the file that needs to be transmitted, so that content loads faster. At any rate, no knowlege nor use of Admiral's scripts were involved in creating the list and addendum thus far.

**Comment by tofof** [comment]
[moved to its own post for clarity and importance]

At any rate, no knowlege nor use of Admiral's scripts were involved in creating the list and addendum thus far. In fact, I would say that the algorithm that produced the list and addendum thus far is superior in that respect to the unknown provenence of the items from pull request #8. I would actually recommend that @paulgb replace that list with the ones derived here, and will shortly create a pull to do so that he can merge if he agrees.

**Comment by paulgb** [comment]
Yes, I would accept that PR. I suspect that most of the entries are
duplicates anyway and it would be good to have the record of provenance.

**Comment by anon182739** [comment]
@tofof
No, the addendum (https://pastebin.com/CYvL1GyJ and https://pastebin.com/Bu2gFH9J) isn't from threatcrowd, it's from using a script to register accounts and get the script domain they use.
>I ran script that created 600 accounts and got the script URLs, these are the only ones in the list. The least common one (jadeitite.com) is present 8 times, the most common one (82o9v830.com) is present 20 times.

**Comment by anon182739** [comment]
>@anon182739 seems focused on the feasibility of maintaining such a list in a hostile environment; throwaways, tor, non-US providers all work toward that goal. That's a potentially valuable process too, but quite in contradiction with the stated goals of this project.

That's true. I was linked here from elsewhere and didn't read the project goals. I'm mostly interested in the technical side of things and what actions give the end result of a more complete list.

**Comment by anon182739** [comment]
Is there any other place where admiral is being discussed? This seems to be the only active github issue about it, are there any active threads elsewhere?  
https://github.com/anon182739/admiraljs - 206 admiral JS files from different domains, might be useful.  They're all identical save for the domain name referenced, so a regex should block them.

**Comment by unicorntaco** [comment]
> It's trivial to observe hundreds of Admiral domains, they probably number in the thousands.


> If someone actually wants to make a serious attempt,


Could not this higher level principle be applied:

This [_exceedingly_ eccentric blog](https://himself.wordpress.com/2016/12/25/merry-holy-christmas-the-end-of-third-party-interweb-ads-forever/) suggests corralling the evil via ASN blocking.  Guilt by association seems like a grand idea, but implementing it is not in my wheelhouse. 


@tofof @paulgb @anon182739

**Comment by TNW9imKLC3fv** [comment]
This was released on 2018-11-01 updated day after: https://github.com/jkrejcha/AdmiraList - but hasn't been updated since then.

(Using [NoScript](https://addons.mozilla.org/en-US/firefox/addon/noscript/), I saw Issu using a creepy-sounding domain 'shallowsmile.com' and found this thread)

**Comment by anon182739** [comment]
There is no need to block any ASNs. It is sufficient to register a few hundred accounts with fake information and see which domains are being offered.
